[build]
  base = "frontend" # Directory containing `package.json` and source files
  publish = "frontend/build" # Directory where the build files are located
  command = "npm run build" # Build command to generate the production build
  functions = "functions" # Directory containing the serverless functions

[dev]
  framework = "vite" # Framework specification for local development

# Optional: Redirects for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
